import { useEffect, useState } from 'react';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api, money, Product } from './api';
import './admin.css';
import './admin-frame.css';

type Admin = { id: number; phone: string; name: string };
type Category = { id: number; name: string };
type DashboardData = { metrics: { paidOrderCount: number; totalSales: number; productCount: number; activeProductCount: number; lowStockCount: number; customerCount: number }; recentOrders: { order_no: string; total: number; status: string; created_at: string }[] };
type ProductForm = { name: string; description: string; price: string; stock: string; emoji: string; categoryId: string; isActive: boolean };
const emptyProduct: ProductForm = { name: '', description: '', price: '', stock: '0', emoji: '📦', categoryId: '', isActive: true };

function AdminLogin({ onLogin }: { onLogin: (admin: Admin) => void }) {
  const [phone, setPhone] = useState(''); const [password, setPassword] = useState(''); const [captcha, setCaptcha] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setPending(true); setError(''); try { const result = await api<{ admin: Admin }>('/admin/auth/login', { method: 'POST', body: JSON.stringify({ phone, password, captcha }) }); onLogin(result.admin); } catch (err: any) { setError(err.message); } finally { setPending(false); } };
  return <main className="admin-login-page"><section className="admin-login-intro"><span>微光集市 · ADMIN</span><h1>让每一次经营，<br />都清晰可见。</h1><p>商品、订单与核心经营指标，集中在一个轻量的演示后台中。</p><div className="admin-login-orb">✦</div></section><form className="admin-login-card" onSubmit={submit}><div className="admin-login-mark">M</div><p className="admin-eyebrow">MANAGEMENT CONSOLE</p><h2>登录管理后台</h2><p className="admin-muted">请输入管理员凭据登录。</p><label>管理员账号<input data-testid="admin-phone-input" value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label>密码<input data-testid="admin-password-input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>验证码 <small>固定为 1234</small><input data-testid="admin-captcha-input" value={captcha} onChange={(event) => setCaptcha(event.target.value)} /></label>{error && <p className="admin-error" role="alert">{error}</p>}<button data-testid="admin-login-submit" className="admin-primary admin-login-button" disabled={pending}>{pending ? '正在登录…' : '登录后台'}</button><p className="admin-hint">管理员：13900000001 / Admin1234</p></form></main>;
}

function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState('');
  useEffect(() => { api<DashboardData>('/admin/dashboard').then(setData).catch((err) => setError(err.message)); }, []);
  if (error) return <p className="admin-error">{error}</p>; if (!data) return <div className="admin-loading">正在汇总经营数据…</div>;
  const cards = [{ label: '累计成交额', value: money(data.metrics.totalSales), note: '已支付订单金额' }, { label: '已支付订单', value: String(data.metrics.paidOrderCount), note: '全渠道累计订单' }, { label: '商品总数', value: String(data.metrics.productCount), note: `在售 ${data.metrics.activeProductCount} 件` }, { label: '库存预警', value: String(data.metrics.lowStockCount), note: '库存 ≤ 20 件商品' }];
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">OVERVIEW</p><h1>营销数据统计</h1><span>数据来自商城实际订单与商品库存</span></div><div className="admin-date">今日经营概览</div></div><section className="admin-metric-grid">{cards.map((card) => <article className="admin-metric" key={card.label}><span>{card.label}</span><strong>{card.value}</strong><small>{card.note}</small></article>)}</section><section className="admin-dashboard-grid"><article className="admin-panel admin-sales-panel"><div className="admin-panel-heading"><div><h2>成交趋势</h2><p>当前演示数据累计概览</p></div><span className="admin-status-dot">数据同步中</span></div><div className="admin-chart" aria-label="成交金额柱状图"><div className="admin-chart-y"><span>¥{Math.max(500, Math.ceil(data.metrics.totalSales / 100) * 100)}</span><span>¥250</span><span>¥0</span></div><div className="admin-bars"><i style={{ height: '32%' }} /><i style={{ height: '52%' }} /><i style={{ height: '41%' }} /><i style={{ height: '68%' }} /><i style={{ height: '47%' }} /><i style={{ height: `${data.metrics.totalSales ? 88 : 10}%` }} /></div></div><div className="admin-chart-labels"><span>周一</span><span>周二</span><span>周三</span><span>周四</span><span>周五</span><span>累计</span></div></article><article className="admin-panel admin-todo-panel"><h2>经营提醒</h2><div className="admin-todo"><b>{data.metrics.lowStockCount}</b><div><strong>库存需要关注</strong><span>建议优先补充低库存商品</span></div></div><div className="admin-todo"><b>{data.metrics.customerCount}</b><div><strong>累计商城用户</strong><span>用户注册后会自动统计</span></div></div><NavLink to="/admin/products" className="admin-link">前往商品管理 →</NavLink></article></section><section className="admin-panel admin-order-panel"><div className="admin-panel-heading"><div><h2>最近订单</h2><p>已支付订单将实时显示在这里</p></div></div>{data.recentOrders.length ? <table><thead><tr><th>订单号</th><th>订单状态</th><th>成交金额</th><th>创建时间</th></tr></thead><tbody>{data.recentOrders.map((order) => <tr key={order.order_no}><td>{order.order_no}</td><td><span className="admin-pill">{order.status}</span></td><td>{money(order.total)}</td><td>{new Date(order.created_at).toLocaleString('zh-CN')}</td></tr>)}</tbody></table> : <p className="admin-empty">还没有订单</p>}</section></>;
}

function ProductEditor({ product, categories, onClose, onSaved, embedded = false }: { product: Product | null; categories: Category[]; onClose: () => void; onSaved: () => void; embedded?: boolean }) {
  const [form, setForm] = useState<ProductForm>(product ? { name: product.name, description: product.description, price: String(product.price), stock: String(product.stock), emoji: product.emoji, categoryId: String(product.category_id), isActive: Boolean(product.is_active) } : { ...emptyProduct, categoryId: categories[0] ? String(categories[0].id) : '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (product || embedded) return; const receive = (event: MessageEvent<{ type?: string }>) => { if (event.origin !== window.location.origin) return; if (event.data?.type === 'admin-product-created') onSaved(); if (event.data?.type === 'admin-product-create-cancel') onClose(); }; window.addEventListener('message', receive); return () => window.removeEventListener('message', receive); }, [embedded, onClose, onSaved, product]);
  if (!product && !embedded) return <section className="admin-iframe-workspace"><header><div><p className="admin-eyebrow">PRODUCT</p><h2>添加商品</h2></div><button data-testid="admin-close-product-frame" className="admin-secondary" onClick={onClose}>返回商品列表</button></header><iframe data-testid="admin-product-create-frame" title="添加商品页面" src="/admin/products/new?embedded=1" /></section>;
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await api(product ? `/admin/products/${product.id}` : '/admin/products', { method: product ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, categoryId: Number(form.categoryId), price: Number(form.price), stock: Number(form.stock) }) }); onSaved(); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };
  const formContent = <form className="admin-product-modal" onSubmit={save}><div className="admin-modal-heading"><div><p className="admin-eyebrow">PRODUCT</p><h2>{product ? '编辑商品' : '添加商品'}</h2></div><button type="button" aria-label="关闭" onClick={onClose}>×</button></div><div className="admin-form-grid"><label>商品名称<input data-testid="admin-product-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>商品分类<select data-testid="admin-product-category" value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>价格（元）<input data-testid="admin-product-price" required min="0" step="0.01" type="number" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /></label><label>库存（件）<input data-testid="admin-product-stock" required min="0" step="1" type="number" value={form.stock} onChange={(event) => setForm({ ...form, stock: event.target.value })} /></label><label>商品图标<input data-testid="admin-product-emoji" required value={form.emoji} onChange={(event) => setForm({ ...form, emoji: event.target.value })} /></label><label className="admin-checkbox"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} />上架销售</label><label className="admin-full">商品描述<textarea data-testid="admin-product-description" required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>{error && <p className="admin-error" role="alert">{error}</p>}<div className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={onClose}>取消</button><button data-testid="admin-save-product" className="admin-primary" disabled={saving}>{saving ? '保存中…' : '保存商品'}</button></div></form>;
  return embedded ? <main className="admin-embedded-product-page">{formContent}</main> : <div className="admin-modal-backdrop" role="presentation">{formContent}</div>;
}

function ProductCreatePage({ embedded = false }: { embedded?: boolean }) {
  const navigate = useNavigate(); const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState('');
  useEffect(() => { api<{ categories: Category[] }>('/categories').then((result) => setCategories(result.categories)).catch((err) => setError(err.message)); }, []);
  const finish = (type: 'admin-product-created' | 'admin-product-create-cancel') => { if (embedded && window.parent !== window) window.parent.postMessage({ type }, window.location.origin); else navigate('/admin/products'); };
  if (error) return <p className="admin-error">{error}</p>; if (!categories.length) return <div className="admin-loading">正在加载商品分类…</div>;
  return <ProductEditor product={null} categories={categories} embedded={embedded} onClose={() => finish('admin-product-create-cancel')} onSaved={() => finish('admin-product-created')} />;
}

function ProductManagement() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [query, setQuery] = useState(''); const [categoryId, setCategoryId] = useState(''); const [status, setStatus] = useState(''); const [editing, setEditing] = useState<Product | null | undefined>(undefined); const [error, setError] = useState('');
  const load = async () => { try { setError(''); const params = new URLSearchParams(); if (query) params.set('q', query); if (categoryId) params.set('categoryId', categoryId); if (status) params.set('status', status); const [productResult, categoryResult] = await Promise.all([api<{ products: Product[] }>(`/admin/products?${params}`), api<{ categories: Category[] }>('/categories')]); setProducts(productResult.products); setCategories(categoryResult.categories); } catch (err: any) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const toggle = async (product: Product) => { try { await api(`/admin/products/${product.id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive: !product.is_active }) }); await load(); } catch (err: any) { setError(err.message); } };
  return <><div className="admin-page-title"><div><p className="admin-eyebrow">CATALOG</p><h1>商品管理</h1><span>维护商城正在售卖的商品、价格和库存</span></div><button data-testid="admin-add-product" className="admin-primary" onClick={() => setEditing(null)}>＋ 添加商品</button></div><section className="admin-panel"><div className="admin-filter-bar"><input data-testid="admin-product-search" placeholder="搜索商品名称或描述" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} /><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">全部分类</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option><option value="active">销售中</option><option value="inactive">已下架</option></select><button className="admin-secondary" onClick={load}>查询</button></div>{error && <p className="admin-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-product-table"><thead><tr><th>商品</th><th>分类</th><th>售价</th><th>库存</th><th>状态</th><th>操作</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} data-testid={`admin-product-row-${product.id}`}><td><div className="admin-product-name"><span>{product.emoji}</span><div><strong>{product.name}</strong><small>{product.description}</small></div></div></td><td>{product.categoryName}</td><td className="admin-price">{money(product.price)}</td><td><span className={product.stock <= 20 ? 'admin-stock-warning' : ''}>{product.stock}</span></td><td><span className={product.is_active ? 'admin-pill' : 'admin-pill admin-pill-muted'}>{product.is_active ? '销售中' : '已下架'}</span></td><td className="admin-actions"><button data-testid={`admin-edit-product-${product.id}`} onClick={() => setEditing(product)}>编辑</button><button onClick={() => toggle(product)}>{product.is_active ? '下架' : '上架'}</button></td></tr>)}</tbody></table>{!products.length && <p className="admin-empty">没有匹配的商品</p>}</div></section>{editing !== undefined && <ProductEditor product={editing} categories={categories} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); load(); }} />}</>;
}

function AdminShell({ admin, onLogout }: { admin: Admin; onLogout: () => void }) {
  const navigate = useNavigate(); const logout = async () => { await api('/admin/auth/logout', { method: 'POST' }); onLogout(); navigate('/admin/login'); };
  return <div className="admin-shell"><aside className="admin-sidebar"><NavLink to="/admin" className="admin-brand"><i>✦</i><span>微光集市<small>管理后台</small></span></NavLink><p className="admin-menu-label">工作台</p><NavLink end to="/admin" className="admin-menu-item">⌂ <span>经营概览</span></NavLink><p className="admin-menu-label">商城管理</p><NavLink data-testid="admin-products-nav" to="/admin/products" className="admin-menu-item">▣ <span>商品管理</span></NavLink><div className="admin-sidebar-foot"><span className="admin-avatar">管</span><div><strong>{admin.name}</strong><small>管理员</small></div><button title="退出登录" onClick={logout}>↪</button></div></aside><main className="admin-content"><header className="admin-topbar"><span>商城经营中心</span><div><span className="admin-live-dot" /> 数据已同步</div></header><div className="admin-page"><Routes><Route path="/admin" element={<Dashboard />} /><Route path="/admin/products" element={<ProductManagement />} /><Route path="*" element={<Navigate to="/admin" replace />} /></Routes></div></main></div>;
}

function AdminRouter() {
  const [admin, setAdmin] = useState<Admin | null>(null); const [ready, setReady] = useState(false);
  useEffect(() => { api<{ admin: Admin | null }>('/admin/auth/me').then((result) => setAdmin(result.admin)).finally(() => setReady(true)); }, []);
  if (!ready) return <div className="admin-loading">正在验证管理员身份…</div>;
  const embedded = new URLSearchParams(window.location.search).get('embedded') === '1';
  return admin ? (embedded ? <ProductCreatePage embedded /> : <AdminShell admin={admin} onLogout={() => setAdmin(null)} />) : <Routes><Route path="/admin/login" element={<AdminLogin onLogin={setAdmin} />} /><Route path="*" element={<Navigate to="/admin/login" replace />} /></Routes>;
}

export function AdminApp() { return <BrowserRouter><AdminRouter /></BrowserRouter>; }
