import { StrictMode, createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { Address, api, CartItem, money, Product, User } from './api';
import './styles.css';

type AppContext = { user: User | null; refreshUser: () => Promise<void>; cartCount: number; refreshCart: () => Promise<void> };
const Context = createContext<AppContext>(null!);
const useApp = () => useContext(Context);

function Notice({ message }: { message: string }) { return <p className="notice" role="alert">{message}</p>; }
function Header() {
  const { user, refreshUser, cartCount } = useApp(); const navigate = useNavigate(); const [query, setQuery] = useState('');
  const logout = async () => { await api('/auth/logout', { method: 'POST' }); await refreshUser(); navigate('/'); };
  return <header><div className="topbar"><Link className="brand" to="/">微光集市</Link><nav><Link to="/products">全部商品</Link><Link to="/orders">我的订单</Link><Link to="/account/addresses">地址簿</Link></nav><form className="search" onSubmit={(e) => { e.preventDefault(); navigate(`/products?q=${encodeURIComponent(query)}`); }}><label className="sr-only" htmlFor="site-search">搜索商品</label><input id="site-search" data-testid="search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索你想要的好物"/><button data-testid="search-submit">搜索</button></form><Link className="cart-link" data-testid="cart-link" to="/cart">购物车 <b>{cartCount}</b></Link>{user ? <button className="link-button" onClick={logout} data-testid="logout-button">退出（{user.name}）</button> : <Link data-testid="login-link" to="/login">登录 / 注册</Link>}</div></header>;
}
function Layout({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><footer>微光集市 · 稳定的本地自动化测试演示商城</footer></>; }
function useProducts(query = '') { const [products, setProducts] = useState<Product[]>([]); useEffect(() => { api<{ products: Product[] }>(`/products${query}`).then((r) => setProducts(r.products)); }, [query]); return products; }
function ProductCard({ product }: { product: Product }) { return <article className="product-card" data-testid={`product-card-${product.id}`}><Link to={`/products/${product.id}`}><div className="product-emoji">{product.emoji}</div><span className="category">{product.categoryName}</span><h3>{product.name}</h3><p>{product.description}</p><strong>{money(product.price)}</strong></Link></article>; }
function Home() { const products = useProducts(); const [categories, setCategories] = useState<any[]>([]); useEffect(() => { api<{categories:any[]}>('/categories').then((r) => setCategories(r.categories)); }, []); return <><section className="hero"><div><span>LOCAL SHOP DEMO</span><h1>把自动化测试，做得稳定又好看。</h1><p>完整购物链路、固定数据、无外部依赖。</p><Link className="primary" to="/products">开始挑选</Link></div><div className="hero-orb">✦</div></section><section><div className="section-title"><h2>分类探索</h2><Link to="/products">查看全部</Link></div><div className="category-grid">{categories.map((c) => <Link key={c.id} data-testid={`category-${c.id}`} to={`/products?categoryId=${c.id}`}>{c.name}</Link>)}</div></section><section><div className="section-title"><h2>精选好物</h2><span>24 件固定种子商品</span></div><div className="product-grid">{products.slice(0, 8).map((p) => <ProductCard product={p} key={p.id}/>)}</div></section></>; }
function Products() { const [params] = useSearchParams(); const q = params.get('q') || ''; const categoryId = params.get('categoryId') || ''; const products = useProducts(`?q=${encodeURIComponent(q)}${categoryId ? `&categoryId=${categoryId}` : ''}`); return <section><div className="page-heading"><p>商品目录</p><h1>{q ? `“${q}” 的搜索结果` : '发现日常好物'}</h1></div>{products.length ? <div className="product-grid">{products.map((p) => <ProductCard product={p} key={p.id}/>)}</div> : <div className="empty" data-testid="empty-search">没有找到匹配商品，换个关键词试试。</div>}</section>; }
function Auth({ mode }: { mode: 'login' | 'register' }) {
  const { refreshUser } = useApp(); const navigate = useNavigate(); const [error, setError] = useState(''); const [form, setForm] = useState({ phone: '', password: '', confirmPassword: '', captcha: '', name: '' });
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); try { await api(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(form) }); await refreshUser(); navigate('/'); } catch (err: any) { setError(err.message); } };
  return <div className="auth-wrap"><form className="auth-card" onSubmit={submit}><p className="eyebrow">微光集市</p><h1>{mode === 'login' ? '欢迎回来' : '创建新账号'}</h1><p>{mode === 'login' ? '使用演示账号体验完整下单流程。' : '注册后即可开始你的购物练习。'}</p>{mode === 'register' && <label>昵称<input data-testid="register-name" value={form.name} onChange={(e) => setForm({...form, name:e.target.value})} placeholder="例如：小光"/></label>}<label>手机号码<input data-testid="phone-input" value={form.phone} onChange={(e) => setForm({...form, phone:e.target.value})} placeholder="11 位手机号码"/></label><label>密码<input data-testid="password-input" type="password" value={form.password} onChange={(e) => setForm({...form, password:e.target.value})} placeholder="至少 6 位"/></label>{mode === 'register' && <label>确认密码<input data-testid="confirm-password-input" type="password" value={form.confirmPassword} onChange={(e) => setForm({...form, confirmPassword:e.target.value})}/></label>}<label>验证码 <span className="captcha">固定验证码：1234</span><input data-testid="captcha-input" value={form.captcha} onChange={(e) => setForm({...form, captcha:e.target.value})} placeholder="请输入 1234"/></label>{error && <Notice message={error}/>}<button className="primary wide" data-testid={mode === 'login' ? 'login-submit' : 'register-submit'}>{mode === 'login' ? '登 录' : '同意协议并注册'}</button><p>{mode === 'login' ? <>还没有账号？<Link to="/register">立即注册</Link></> : <>已有账号？<Link to="/login">去登录</Link></>}</p><small>演示账号：13800000000 / Demo1234</small></form></div>;
}
function ProductDetail() { const id = Number(useLocation().pathname.split('/').pop()); const [product, setProduct] = useState<Product | null>(null); const { user, refreshCart } = useApp(); const navigate = useNavigate(); const [message, setMessage] = useState(''); const [quantity, setQuantity] = useState(1); useEffect(() => { api<Product>(`/products/${id}`).then(setProduct).catch((e) => setMessage(e.message)); }, [id]); if (!product) return <div className="empty">{message || '正在加载商品…'}</div>; const add = async () => { if (!user) return navigate('/login'); try { await api('/cart', { method: 'POST', body: JSON.stringify({ productId: product.id, quantity }) }); await refreshCart(); setMessage('已加入购物车'); } catch (err: any) { setMessage(err.message); } }; return <section className="detail"><div className="detail-emoji">{product.emoji}</div><div><span className="category">{product.categoryName}</span><h1>{product.name}</h1><p className="detail-desc">{product.description}</p><strong className="price">{money(product.price)}</strong><p>剩余库存：<b data-testid="product-stock">{product.stock}</b></p><label>购买数量 <input data-testid="quantity-input" type="number" min="1" max={product.stock} value={quantity} onChange={(e) => setQuantity(Number(e.target.value))}/></label><button className="primary" data-testid="add-to-cart" onClick={add}>加入购物车</button>{message && <Notice message={message}/>}</div></section>; }
function RequireAuth({ children }: { children: React.ReactNode }) { const { user } = useApp(); const location = useLocation(); return user ? <>{children}</> : <Navigate to="/login" state={{ from: location.pathname }} replace/>; }
function Cart() { const { refreshCart } = useApp(); const [items, setItems] = useState<CartItem[]>([]); const [message, setMessage] = useState(''); const navigate = useNavigate(); const load = () => api<{items: CartItem[]}>('/cart').then((r) => setItems(r.items)).catch((e) => setMessage(e.message)); useEffect(() => { load(); }, []); const update = async (item: CartItem, quantity: number) => { try { await api(`/cart/${item.productId}`, { method: 'PATCH', body: JSON.stringify({ quantity }) }); await load(); await refreshCart(); } catch (e: any) { setMessage(e.message); } }; const remove = async (id: number) => { await api(`/cart/${id}`, {method:'DELETE'}); await load(); await refreshCart(); }; const total = items.reduce((s, i) => s + i.price * i.quantity, 0); return <section><div className="page-heading"><p>购物车</p><h1>准备结算的好物</h1></div>{message && <Notice message={message}/>} {!items.length ? <div className="empty" data-testid="empty-cart">购物车还是空的。<Link to="/products">去逛逛</Link></div> : <><div className="cart-list">{items.map((item) => <article className="cart-item" key={item.productId} data-testid={`cart-item-${item.productId}`}><span className="cart-emoji">{item.emoji}</span><div><h3>{item.name}</h3><strong>{money(item.price)}</strong></div><label>数量<input data-testid={`cart-quantity-${item.productId}`} type="number" min="1" max={item.stock} value={item.quantity} onChange={(e) => update(item, Number(e.target.value))}/></label><button className="text-danger" onClick={() => remove(item.productId)}>删除</button></article>)}</div><div className="total-bar"><span>合计 <b data-testid="cart-total">{money(total)}</b></span><button className="primary" data-testid="checkout-button" onClick={() => navigate('/checkout')}>去结算</button></div></>}</section>; }
function Addresses({ selectable = false, onSelect }: { selectable?: boolean; onSelect?: (id: number) => void }) { const [addresses, setAddresses] = useState<Address[]>([]); const [form, setForm] = useState({recipient:'',phone:'',detail:'',isDefault:true}); const [error,setError] = useState(''); const load = () => api<{addresses:Address[]}>('/addresses').then((r) => setAddresses(r.addresses)); useEffect(() => { load(); }, []); const save = async (e: React.FormEvent) => { e.preventDefault(); try { await api('/addresses', {method:'POST',body:JSON.stringify(form)}); setForm({recipient:'',phone:'',detail:'',isDefault:true}); setError(''); load(); } catch (err:any) { setError(err.message); } }; return <div className="addresses"><div className="address-list">{addresses.map((a) => <button key={a.id} data-testid={`address-${a.id}`} className={selectable ? 'address selectable' : 'address'} onClick={() => onSelect?.(a.id)}><b>{a.recipient} · {a.phone}</b><span>{a.detail}</span>{a.is_default ? <small>默认地址</small> : null}</button>)} {!addresses.length && <div className="empty">还没有地址，请先新增。</div>}</div><form className="address-form" onSubmit={save}><h2>新增收货地址</h2><label>收货人<input data-testid="address-recipient" value={form.recipient} onChange={(e)=>setForm({...form,recipient:e.target.value})}/></label><label>手机号码<input data-testid="address-phone" value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label>详细地址<textarea data-testid="address-detail" value={form.detail} onChange={(e)=>setForm({...form,detail:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={form.isDefault} onChange={(e)=>setForm({...form,isDefault:e.target.checked})}/>设为默认地址</label>{error && <Notice message={error}/>}<button data-testid="add-address" className="primary">保存地址</button></form></div>; }
function AddressPage() { return <section><div className="page-heading"><p>账户设置</p><h1>收货地址簿</h1></div><Addresses/></section>; }
function Checkout() { const navigate = useNavigate(); const [addressId,setAddressId] = useState<number | null>(null); const [message,setMessage] = useState(''); const checkout = async () => { try { const r = await api<{order:{id:number;orderNo:string}}>('/checkout',{method:'POST',body:JSON.stringify({addressId})}); navigate(`/orders?created=${r.order.orderNo}`); } catch(e:any){setMessage(e.message);} }; return <section><div className="page-heading"><p>确认订单</p><h1>选择收货地址</h1></div><p>点击一张地址卡片后，使用本地模拟支付完成下单。</p><Addresses selectable onSelect={setAddressId}/>{message && <Notice message={message}/>}<div className="total-bar"><span>{addressId ? '已选择收货地址' : '请选择地址'}</span><button className="primary" data-testid="pay-button" disabled={!addressId} onClick={checkout}>模拟支付并下单</button></div></section>; }
function Orders() { const [orders,setOrders] = useState<any[]>([]); const [params] = useSearchParams(); useEffect(()=>{api<{orders:any[]}>('/orders').then((r)=>setOrders(r.orders));},[]); return <section><div className="page-heading"><p>订单中心</p><h1>我的订单</h1></div>{params.get('created') && <Notice message={`订单 ${params.get('created')} 已支付成功`}/>}<div className="order-list">{orders.map((o)=> <article className="order" key={o.id} data-testid={`order-${o.order_no}`}><div><span>{o.order_no}</span><h3>{o.status}</h3></div><strong>{money(o.total)}</strong><small>{new Date(o.created_at).toLocaleString('zh-CN')}</small></article>)}</div></section>; }
function App() { const [user,setUser] = useState<User|null>(null); const [cartCount,setCartCount] = useState(0); const refreshUser = async () => { const r = await api<{user:User|null}>('/auth/me'); setUser(r.user); }; const refreshCart = async () => { try { const r=await api<{items:CartItem[]}>('/cart'); setCartCount(r.items.reduce((s,i)=>s+i.quantity,0)); } catch { setCartCount(0); } }; useEffect(()=>{refreshUser();},[]); useEffect(()=>{refreshCart();},[user?.id]); return <Context.Provider value={{user,refreshUser,cartCount,refreshCart}}><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:id" element={<ProductDetail/>}/><Route path="/cart" element={<RequireAuth><Cart/></RequireAuth>}/><Route path="/checkout" element={<RequireAuth><Checkout/></RequireAuth>}/><Route path="/orders" element={<RequireAuth><Orders/></RequireAuth>}/><Route path="/account/addresses" element={<RequireAuth><AddressPage/></RequireAuth>}/></Routes></Layout></Context.Provider>; }
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>);
